#!/bin/bash
# Demo Mainnet Setup Script
# Creates the optimal environment for ML training

echo "🚀 SETTING UP DEMO MAINNET FOR ML TRAINING"
echo "=========================================="
echo ""
echo "💎 Demo on Mainnet is PERFECT for ML training because:"
echo "   ✅ Real market prices and volatility"
echo "   ✅ Real order book dynamics" 
echo "   ✅ Real spreads and slippage"
echo "   ✅ Zero financial risk"
echo "   ✅ Better training data quality"
echo ""
echo "📋 SETUP STEPS:"
echo "1. 🌐 Go to: https://www.bybit.com/app/user/api-management"
echo "2. 🔑 Click 'Create API Key'"
echo "3. ⚡ IMPORTANT: Select 'Demo' option (not 'Live')"
echo "4. 🛡️  Set permissions: Read, Trade"
echo "5. 📝 Copy the API Key and Secret"
echo "6. 🔧 Update .env file with new demo keys"
echo ""
echo "⚙️  CONFIGURATION NEEDED:"
echo "BYBIT_API_KEY=your_demo_key_here"
echo "BYBIT_API_SECRET=your_demo_secret_here"
echo "BYBIT_TESTNET=false"
echo "BYBIT_DEMO=true"
echo "BYBIT_BASE_URL=https://api-demo.bybit.com"
echo ""
echo "🎯 After setup, run: ./deployment/deploy_staging.sh"
echo "   This will launch with real market data and fake funds!"
echo ""
echo "📞 Need help? Check: BYBIT_ENVIRONMENTS.md"